#!/bin/bash

clear

printf "     \e[1;96m If You are getting Error Join our \e[1;91mTelegram Group\e[0m                       \n"
printf "            \e[1;96m Plese Subscribe our \e[1;91mYouTube Channel\e[0m                         \n  \n"

menu() {

printf "\e[1;92m[\e[0m\e[1;77m01\e[0m\e[1;92m]\e[0m\e[1;91m Blackeye\e[0m                                    \n \n"
printf "\e[1;92m[\e[0m\e[1;77m02\e[0m\e[1;92m]\e[0m\e[1;91m AdvPhish\e[0m                                    \n \n"
printf "\e[1;92m[\e[0m\e[1;77m03\e[0m\e[1;92m]\e[0m\e[1;91m SharkPhish\e[0m                                  \n \n"
printf "\e[1;92m[\e[0m\e[1;77m04\e[0m\e[1;92m]\e[0m\e[1;91m Top Phishing Tools\e[0m                          \n \n"
printf "\e[1;92m[\e[0m\e[1;77m05\e[0m\e[1;92m]\e[0m\e[1;91m Top Phispung Tools Link\e[0m                     \n \n"
printf "\e[1;92m[\e[0m\e[1;77m99\e[0m\e[1;92m]\e[0m\e[1;91m BACK\e[0m                                        \n \n"

read -p $'\n\e[1;91m[\e[0m\e[1;96m(◣_◢)\e[0m\e[1;91m] Choose an option: \e[0m\en' option


if [[ $option == 1 ]]; then
termux-open-url https://devilhackers22.blogspot.com/2021/01/blackeye-termux.html
clear
menu

elif [[ $option == 2 ]]; then
termux-open-url https://devilhackers22.blogspot.com/2021/01/advphishing.html
clear
menu

elif [[ $option == 3 ]]; then
termux-open-url https://devilhackers22.blogspot.com/2021/01/shark-phishing.html
clear
menu

elif [[ $option == 4 ]]; then
termux-open-url https://devilhackers22.blogspot.com/2021/01/top-best-phishing-tools.html
clear
menu

elif [[ $option == 5 ]]; then
termux-open-url https://devilhackers22.blogspot.com/2021/01/top-phishing-tools.html
clear
menu

elif [[ $option == 99 ]]; then
cd ..
bash DevilEye

else
printf "\e[1;93m [!] Invalid option!\e[0m\n"
clear
menu
fi
}

menu
